package com.galaxymc.client.render;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * A creature model as generated by tools/mobs/gen_mobs.py: parts (with pivots, rotations, box-UV cubes)
 * and the animation role of each part. Turned into a vanilla {@link LayerDefinition} for baking.
 */
public final class CreatureModelData {
    public record Cube(int u, int v, float x, float y, float z, int w, int h, int d, float inflate) {}

    public record Anim(String role, float phase, float amp, float speed) {}

    public record Part(String name, String parent, float px, float py, float pz, float rx, float ry, float rz, List<Cube> cubes, Anim anim) {}

    public final int texWidth;
    public final int texHeight;
    public final List<Part> parts;

    private static final Map<String, CreatureModelData> CACHE = new HashMap<>();

    private CreatureModelData(int w, int h, List<Part> parts) {
        this.texWidth = w;
        this.texHeight = h;
        this.parts = parts;
    }

    public static synchronized CreatureModelData load(String name) {
        return CACHE.computeIfAbsent(name, CreatureModelData::read);
    }

    private static CreatureModelData read(String name) {
        String path = "/assets/galaxy_mc/creature_models/" + name + ".json";
        try (InputStream in = CreatureModelData.class.getResourceAsStream(path)) {
            if (in == null) {
                throw new IllegalStateException("missing creature model " + path);
            }
            JsonObject root = JsonParser.parseReader(new InputStreamReader(in, StandardCharsets.UTF_8)).getAsJsonObject();
            JsonArray tex = root.getAsJsonArray("texture");
            List<Part> parts = new ArrayList<>();
            for (JsonElement e : root.getAsJsonArray("parts")) {
                JsonObject p = e.getAsJsonObject();
                JsonArray pivot = p.getAsJsonArray("pivot");
                JsonArray rot = p.getAsJsonArray("rot");
                List<Cube> cubes = new ArrayList<>();
                for (JsonElement ce : p.getAsJsonArray("cubes")) {
                    JsonObject c = ce.getAsJsonObject();
                    JsonArray uv = c.getAsJsonArray("uv");
                    JsonArray o = c.getAsJsonArray("origin");
                    JsonArray s = c.getAsJsonArray("size");
                    cubes.add(new Cube(uv.get(0).getAsInt(), uv.get(1).getAsInt(), o.get(0).getAsFloat(), o.get(1).getAsFloat(),
                            o.get(2).getAsFloat(), s.get(0).getAsInt(), s.get(1).getAsInt(), s.get(2).getAsInt(),
                            c.get("inflate").getAsFloat()));
                }
                Anim anim = null;
                if (p.has("anim") && !p.get("anim").isJsonNull()) {
                    JsonObject a = p.getAsJsonObject("anim");
                    anim = new Anim(a.get("role").getAsString(), a.get("phase").getAsFloat(), a.get("amp").getAsFloat(),
                            a.get("speed").getAsFloat());
                }
                parts.add(new Part(p.get("name").getAsString(), p.get("parent").getAsString(), pivot.get(0).getAsFloat(),
                        pivot.get(1).getAsFloat(), pivot.get(2).getAsFloat(), rot.get(0).getAsFloat(), rot.get(1).getAsFloat(),
                        rot.get(2).getAsFloat(), cubes, anim));
            }
            return new CreatureModelData(tex.get(0).getAsInt(), tex.get(1).getAsInt(), List.copyOf(parts));
        } catch (Exception e) {
            throw new IllegalStateException("could not load creature model " + name, e);
        }
    }

    public LayerDefinition layer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        Map<String, PartDefinition> defs = new HashMap<>();
        for (Part p : parts) {
            PartDefinition parent = "root".equals(p.parent()) ? root : defs.getOrDefault(p.parent(), root);
            CubeListBuilder cubes = CubeListBuilder.create();
            for (Cube c : p.cubes()) {
                cubes = cubes.texOffs(c.u(), c.v()).addBox(c.x(), c.y(), c.z(), c.w(), c.h(), c.d(), new CubeDeformation(c.inflate()));
            }
            defs.put(p.name(), parent.addOrReplaceChild(p.name(), cubes, PartPose.offsetAndRotation(p.px(), p.py(), p.pz(), p.rx(), p.ry(), p.rz())));
        }
        return LayerDefinition.create(mesh, texWidth, texHeight);
    }
}
