package com.galaxymc.entity;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import java.util.ArrayList;
import java.util.List;

/**
 * One creature species, as generated by {@code tools/mobs/gen_mobs.py} into data/galaxy_mc/species.json.
 * Species are immutable and indexed; the index is what segmented worms sync to the client so a
 * single segment entity type can render the body of any worm.
 */
public final class Species {
    public enum Kind { GROUND, FLYER, FLOATER, STATIC, WORM }

    public enum Temper { HOSTILE, NEUTRAL, PASSIVE }

    public enum Attack { MELEE, SPIT, NONE }

    public enum WormMode { BURROW, SURFACE, SWIM }

    public final int index;
    public final String id;
    public final String name;
    public final String family;
    public final String element;
    public final String effect;
    public final String plan;
    public final Kind kind;
    public final Temper temper;
    public final Attack attack;
    public final double spitRange;
    public final boolean leap;
    public final boolean charge;
    public final boolean climb;
    public final boolean swim;
    public final boolean hops;
    public final boolean ambush;
    public final boolean giant;
    public final double scale;
    public final float width;
    public final float height;
    public final double health;
    public final double damage;
    public final double speed;
    public final double flySpeed;
    public final double armor;
    public final double knockbackResistance;
    public final double followRange;
    public final double stepHeight;
    public final int groupMin;
    public final int groupMax;
    public final int weight;
    public final int minTier;
    public final List<String> climates;
    public final List<String> types;
    public final List<String> sol;
    public final String voice;
    public final int primary;
    public final int secondary;
    public final int accent;
    public final int eyes;
    public final boolean fireImmune;
    public final String texture;
    public final int segments;
    public final WormMode wormMode;
    public final double spacing;
    public final String segmentTexture;

    Species(int index, JsonObject o) {
        this.index = index;
        this.id = o.get("id").getAsString();
        this.name = o.get("name").getAsString();
        this.family = o.get("family").getAsString();
        this.element = o.get("element").getAsString();
        this.effect = o.get("effect").isJsonNull() ? "" : o.get("effect").getAsString();
        this.plan = o.get("plan").getAsString();
        this.kind = Kind.valueOf(o.get("kind").getAsString().toUpperCase());
        this.temper = Temper.valueOf(o.get("temper").getAsString().toUpperCase());
        this.attack = Attack.valueOf(o.get("attack").getAsString().toUpperCase());
        this.spitRange = o.get("spitRange").getAsDouble();
        this.leap = o.get("leap").getAsBoolean();
        this.charge = o.get("charge").getAsBoolean();
        this.climb = o.get("climb").getAsBoolean();
        this.swim = o.get("swim").getAsBoolean();
        this.hops = o.get("hops").getAsBoolean();
        this.ambush = o.get("ambush").getAsBoolean();
        this.giant = o.get("giant").getAsBoolean();
        this.scale = o.get("scale").getAsDouble();
        this.width = o.get("width").getAsFloat();
        this.height = o.get("height").getAsFloat();
        this.health = o.get("health").getAsDouble();
        this.damage = o.get("damage").getAsDouble();
        this.speed = o.get("speed").getAsDouble();
        this.flySpeed = o.get("flySpeed").getAsDouble();
        this.armor = o.get("armor").getAsDouble();
        this.knockbackResistance = o.get("knockbackResistance").getAsDouble();
        this.followRange = o.get("followRange").getAsDouble();
        this.stepHeight = o.get("stepHeight").getAsDouble();
        JsonArray group = o.getAsJsonArray("group");
        this.groupMin = group.get(0).getAsInt();
        this.groupMax = group.get(1).getAsInt();
        this.weight = o.get("weight").getAsInt();
        this.minTier = o.get("minTier").getAsInt();
        this.climates = strings(o.getAsJsonArray("climates"));
        this.types = strings(o.getAsJsonArray("types"));
        this.sol = strings(o.getAsJsonArray("sol"));
        this.voice = o.get("voice").getAsString();
        JsonObject c = o.getAsJsonObject("colours");
        this.primary = colour(c, "primary");
        this.secondary = colour(c, "secondary");
        this.accent = colour(c, "accent");
        this.eyes = colour(c, "eyes");
        this.fireImmune = o.get("fireImmune").getAsBoolean();
        this.texture = o.get("texture").getAsString();
        if (o.has("worm")) {
            JsonObject w = o.getAsJsonObject("worm");
            this.segments = w.get("segments").getAsInt();
            this.wormMode = WormMode.valueOf(w.get("mode").getAsString().toUpperCase());
            this.spacing = w.get("spacing").getAsDouble();
            this.segmentTexture = w.get("segmentTexture").getAsString();
        } else {
            this.segments = 0;
            this.wormMode = null;
            this.spacing = 0;
            this.segmentTexture = null;
        }
    }

    private static List<String> strings(JsonArray a) {
        List<String> out = new ArrayList<>();
        if (a != null) {
            for (JsonElement e : a) {
                out.add(e.getAsString());
            }
        }
        return List.copyOf(out);
    }

    private static int colour(JsonObject o, String key) {
        return Integer.parseInt(o.get(key).getAsString().substring(1), 16);
    }

    public boolean hostile() {
        return temper == Temper.HOSTILE;
    }

    public boolean passive() {
        return temper == Temper.PASSIVE;
    }

    public boolean flies() {
        return kind == Kind.FLYER || kind == Kind.FLOATER;
    }

    /** Movement speed attribute: giants take proportionally longer strides. */
    public double movementSpeed() {
        return giant ? speed * Math.pow(scale, 0.35) : speed;
    }

    public boolean fitsClimate(String climate) {
        return climates.contains(climate);
    }
}
