"""The Galaxy MC bestiary: families of creatures and the element variants that spin them off.

A family fixes the body plan, behaviour and base stats; a variant supplies an element (which drives
colours, adornments, on-hit effects and preferred climates), a name and optional overrides (a size
multiplier turns a Weaver into a Giant Weaver). Everything else - models, textures, loot, lang,
spawn eggs - is generated from this table by gen_mobs.py.
"""

ALL_CLIMATES = ["scorching", "hot", "temperate", "cold", "frozen"]

# element -> (primary, secondary, accent, eyes), climates, on-hit effect tag
ELEMENTS = {
    "plain": ((0x8a7a66, 0xc8b89a, 0x5a4a3a, 0xffe060), ["temperate", "hot", "cold"], None),
    "dusk": ((0x3a3050, 0x6a5a8a, 0x201830, 0xff4060), ["temperate", "cold", "hot"], "blind"),
    "shadow": ((0x1a1a22, 0x3a3a4a, 0x0a0a10, 0xff2020), ALL_CLIMATES, "blind"),
    "frost": ((0xb8d8f0, 0xeaf6ff, 0x6a9ac8, 0x60e0ff), ["cold", "frozen"], "frost"),
    "ember": ((0x8a2a10, 0xe0601a, 0x3a1008, 0xffd040), ["hot", "scorching"], "fire"),
    "magma": ((0x2a1a18, 0xff5a10, 0x100808, 0xffa020), ["scorching", "hot"], "fire"),
    "toxic": ((0x5a8a1a, 0xb8e030, 0x2a4a0a, 0xe0ff40), ["temperate", "hot"], "poison"),
    "crystal": ((0x6ac0e8, 0xd0f4ff, 0x3a6aa8, 0xffffff), ALL_CLIMATES, "armor"),
    "void": ((0x20102a, 0x7a3aca, 0x080410, 0xd080ff), ALL_CLIMATES, "void"),
    "storm": ((0x4a5a7a, 0xa8c0e8, 0x2a3048, 0xa0f0ff), ["temperate", "cold", "hot"], "storm"),
    "glow": ((0x1a4a4a, 0x40f0c0, 0x0a2020, 0xa0ffe0), ALL_CLIMATES, "glow"),
    "sand": ((0xc8a060, 0xe8d0a0, 0x8a6a3a, 0x202020), ["hot", "scorching", "temperate"], None),
    "ash": ((0x4a4644, 0x8a8480, 0x2a2624, 0xff6a20), ["hot", "scorching"], "fire"),
    "iron": ((0x6a6a70, 0xa8a8b0, 0x3a3a40, 0xffa040), ALL_CLIMATES, "armor"),
    "moss": ((0x3a6a2a, 0x7ab04a, 0x1a3a10, 0xffe060), ["temperate"], "poison"),
    "aurora": ((0x2a5a6a, 0x80e0c0, 0x1a2a4a, 0xff80ff), ["cold", "frozen", "temperate"], "glow"),
    "gold": ((0xb08a20, 0xf0d060, 0x6a4a10, 0xffffff), ["hot", "temperate"], "armor"),
    "blood": ((0x6a0a10, 0xc02030, 0x300408, 0xffe0a0), ["temperate", "hot"], None),
    "stone": ((0x6a6660, 0x9a968e, 0x3a3834, 0xffa040), ALL_CLIMATES, "armor"),
    "jungle": ((0x2a5a20, 0x6aa040, 0x1a3010, 0xffd020), ["temperate"], "poison"),
    "lunar": ((0x8a8a8e, 0xc0c0c4, 0x5a5a5e, 0x80c0ff), ALL_CLIMATES, None),
    "deep": ((0x102a4a, 0x2a6aa0, 0x081020, 0x60ffff), ALL_CLIMATES, None),
}

# ---------------------------------------------------------------------------------------------- families
# Each family: plan, params, kind (ground | flyer | floater | static | worm), temper, attack, base stats,
# group size, weight, drops, voice, and variants [(element, display name, overrides)].

FAMILIES = [
    dict(id="stalker", name="Stalker", plan="quadruped", kind="ground", temper="hostile", attack="melee", leap=True,
         params=dict(body_len=14, body_w=7, body_h=7, leg_len=10, leg_w=3, head=7, snout=4, jaw=True, tail=10, stride=1.2),
         health=24, damage=5, speed=0.33, armor=2, group=(1, 2), weight=8, drops=["xeno_meat", "xeno_hide"], voice="zoglin",
         variants=[("dusk", "Dusk Stalker", {}), ("frost", "Frost Stalker", {}), ("ember", "Ember Stalker", {}),
                   ("void", "Void Stalker", {"min_tier": 3}), ("crystal", "Crystal Stalker", {}), ("toxic", "Toxic Stalker", {}),
                   ("shadow", "Shadow Stalker", {"min_tier": 2}), ("storm", "Storm Stalker", {})]),
    dict(id="grazer", name="Grazer", plan="quadruped", kind="ground", temper="passive", attack="none",
         params=dict(body_len=18, body_w=12, body_h=11, leg_len=9, leg_w=4, head=8, snout=3, neck=5, tail=5, stride=0.8),
         health=22, damage=0, speed=0.22, armor=1, group=(2, 5), weight=14, drops=["xeno_meat", "xeno_hide"], voice="camel",
         variants=[("plain", "Plains Grazer", {}), ("frost", "Woolly Grazer", {"drops": ["xeno_meat", "thermal_fiber"]}),
                   ("sand", "Dune Grazer", {}), ("moss", "Moss Grazer", {}), ("crystal", "Crystal Grazer", {}),
                   ("ash", "Ash Grazer", {}), ("toxic", "Bloat Grazer", {}), ("aurora", "Aurora Grazer", {})]),
    dict(id="hound", name="Hound", plan="quadruped", kind="ground", temper="hostile", attack="melee",
         params=dict(body_len=11, body_w=6, body_h=6, leg_len=7, leg_w=2, head=6, snout=3, jaw=True, tail=6, stride=1.3),
         health=14, damage=3, speed=0.36, armor=1, group=(3, 5), weight=10, drops=["xeno_meat"], voice="hoglin",
         variants=[("stone", "Rock Hound", {}), ("frost", "Frost Hound", {}), ("ash", "Ash Hound", {}),
                   ("glow", "Glow Hound", {}), ("toxic", "Plague Hound", {}), ("void", "Void Hound", {"min_tier": 3})]),
    dict(id="ramhorn", name="Ramhorn", plan="quadruped", kind="ground", temper="neutral", attack="melee", charge=True,
         params=dict(body_len=16, body_w=11, body_h=10, leg_len=8, leg_w=4, head=9, snout=2, stride=0.9),
         health=36, damage=7, speed=0.25, armor=6, group=(1, 3), weight=7, drops=["xeno_meat", "chitin_plate"], voice="goat",
         variants=[("stone", "Ramhorn", {}), ("iron", "Iron Ramhorn", {}), ("magma", "Magma Ramhorn", {})]),
    dict(id="behemoth", name="Behemoth", plan="quadruped", kind="ground", temper="neutral", attack="melee", giant=True,
         params=dict(body_len=22, body_w=16, body_h=14, leg_len=12, leg_w=6, head=10, snout=3, jaw=True, tail=8, stride=0.6),
         health=260, damage=18, speed=0.2, armor=10, group=(1, 1), weight=2, scale=4.5, min_tier=2,
         drops=["titan_core", "xeno_hide", "xeno_meat"], voice="ravager",
         variants=[("stone", "Stone Behemoth", {}), ("frost", "Glacier Behemoth", {}), ("magma", "Lava Behemoth", {}),
                   ("jungle", "Jungle Behemoth", {})]),
    dict(id="titan", name="Titan", plan="quadruped", kind="ground", temper="neutral", attack="melee", giant=True,
         params=dict(body_len=26, body_w=18, body_h=16, leg_len=16, leg_w=7, head=11, neck=6, tail=14, stride=0.5, leg_pairs=3),
         health=900, damage=34, speed=0.18, armor=16, group=(1, 1), weight=1, scale=11.0, min_tier=4,
         drops=["titan_core", "titan_core", "leviathan_scale"], voice="ender_dragon",
         variants=[("stone", "World Titan", {}), ("frost", "Ice Titan", {"scale": 9.5})]),
    dict(id="hopper", name="Hopper", plan="quadruped", kind="ground", temper="passive", attack="none", hops=True,
         params=dict(body_len=7, body_w=5, body_h=5, leg_len=3, leg_w=2, head=5, tail=2, stride=1.4),
         health=6, damage=0, speed=0.3, armor=0, group=(2, 4), weight=12, drops=["xeno_meat"], voice="armadillo",
         variants=[("stone", "Rock Hopper", {}), ("frost", "Snow Hopper", {}), ("sand", "Dune Hopper", {}),
                   ("lunar", "Moon Hopper", {"sol": ["moon"]})]),
    dict(id="beetle", name="Beetle", plan="insect", kind="ground", temper="neutral", attack="melee",
         params=dict(body_len=16, body_w=10, body_h=6, leg_len=6, head=5, mandibles=True, antennae=True),
         health=20, damage=4, speed=0.24, armor=8, group=(1, 3), weight=9, drops=["chitin_plate"], voice="silverfish",
         variants=[("gold", "Scarab", {}), ("iron", "Iron Beetle", {}), ("crystal", "Crystal Beetle", {}),
                   ("magma", "Magma Beetle", {}), ("frost", "Frost Beetle", {}), ("toxic", "Blister Beetle", {}),
                   ("void", "Void Beetle", {"min_tier": 3})]),
    dict(id="mantis", name="Mantis", plan="insect", kind="ground", temper="hostile", attack="melee", leap=True,
         params=dict(body_len=14, body_w=5, body_h=5, leg_len=8, head=5, blades=True, antennae=True),
         health=22, damage=7, speed=0.34, armor=3, group=(1, 2), weight=6, drops=["chitin_plate", "venom_sac"], voice="endermite",
         variants=[("jungle", "Blade Mantis", {}), ("aurora", "Orchid Mantis", {}), ("ash", "Ash Mantis", {})]),
    dict(id="drone", name="Drone", plan="insect", kind="ground", temper="hostile", attack="melee",
         params=dict(body_len=9, body_w=5, body_h=4, leg_len=5, head=4, mandibles=True, antennae=True),
         health=10, damage=3, speed=0.34, armor=2, group=(4, 7), weight=9, drops=["chitin_plate"], voice="silverfish",
         variants=[("blood", "Soldier Drone", {}), ("sand", "Worker Drone", {"temper": "neutral"}),
                   ("blood", "Hive Queen", {"scale": 3.2, "health": 120, "damage": 9, "giant": True, "group": (1, 1), "weight": 2,
                                            "min_tier": 2, "drops": ["chitin_plate", "venom_sac", "titan_core"]})]),
    dict(id="weaver", name="Weaver", plan="arachnid", kind="ground", temper="hostile", attack="melee", climb=True,
         params=dict(body_len=14, body_w=9, body_h=6, leg_len=12, head=5),
         health=18, damage=4, speed=0.32, armor=2, group=(1, 3), weight=9, drops=["venom_sac", "xeno_hide"], voice="spider",
         variants=[("stone", "Cave Weaver", {}), ("frost", "Frost Weaver", {}), ("magma", "Lava Weaver", {}),
                   ("void", "Void Weaver", {"min_tier": 3}), ("crystal", "Crystal Weaver", {}), ("toxic", "Plague Weaver", {}),
                   ("shadow", "Giant Weaver", {"scale": 3.5, "health": 110, "damage": 11, "giant": True, "weight": 2, "min_tier": 2,
                                               "group": (1, 1)})]),
    dict(id="scorpion", name="Scorpion", plan="insect", kind="ground", temper="hostile", attack="spit", spit_range=10,
         params=dict(body_len=16, body_w=8, body_h=5, leg_len=7, head=5, stinger=True, blades=True),
         health=24, damage=5, speed=0.28, armor=5, group=(1, 2), weight=8, drops=["chitin_plate", "venom_sac"], voice="spider",
         variants=[("sand", "Dune Scorpion", {"sol": ["mars"]}), ("ember", "Ember Scorpion", {}),
                   ("gold", "Emperor Scorpion", {"scale": 3.0, "health": 140, "damage": 12, "giant": True, "weight": 2,
                                                 "min_tier": 2, "group": (1, 1)})]),
    dict(id="grey", name="Grey", plan="biped", kind="ground", temper="hostile", attack="spit", spit_range=16,
         params=dict(body_h=10, body_w=6, body_d=3, leg_len=10, leg_w=2, head=8, head_w=1.1, arm_len=11, arm_w=2),
         health=20, damage=4, speed=0.27, armor=1, group=(1, 3), weight=5, drops=["glow_spore"], voice="vex", min_tier=2,
         variants=[("lunar", "Grey Watcher", {}), ("void", "Grey Seer", {"min_tier": 3})]),
    dict(id="golem", name="Golem", plan="biped", kind="ground", temper="neutral", attack="melee",
         params=dict(body_h=14, body_w=14, body_d=8, leg_len=10, leg_w=5, head=8, arm_len=16, arm_w=5),
         health=80, damage=12, speed=0.2, armor=12, group=(1, 1), weight=4, drops=["chitin_plate"], voice="warden", scale=1.3,
         variants=[("stone", "Rock Golem", {}), ("crystal", "Crystal Golem", {}), ("magma", "Magma Golem", {}),
                   ("frost", "Ice Golem", {}), ("void", "Void Golem", {"min_tier": 3}),
                   ("iron", "Colossus", {"scale": 7.0, "health": 600, "damage": 28, "giant": True, "weight": 1, "min_tier": 4,
                                         "drops": ["titan_core", "titan_core"]})]),
    dict(id="raptor", name="Raptor", plan="biped", kind="ground", temper="hostile", attack="melee", leap=True,
         params=dict(body_h=8, body_w=6, body_d=12, leg_len=9, leg_w=3, head=6, snout=5, jaw=True, lean=1.1, tail=12, arm_len=5, arm_w=1),
         health=22, damage=5, speed=0.37, armor=2, group=(2, 4), weight=8, drops=["xeno_meat", "xeno_hide"], voice="ravager",
         variants=[("sand", "Sand Raptor", {}), ("frost", "Frost Raptor", {}), ("jungle", "Jungle Raptor", {}), ("ash", "Ash Raptor", {}),
                   ("blood", "Tyrant", {"scale": 4.0, "health": 220, "damage": 20, "giant": True, "weight": 2, "min_tier": 3,
                                        "group": (1, 1), "drops": ["titan_core", "xeno_hide", "xeno_meat"]})]),
    dict(id="strider", name="Strider", plan="tripod", kind="ground", temper="passive", attack="none",
         params=dict(body=12, leg_len=26),
         health=40, damage=0, speed=0.2, armor=2, group=(1, 3), weight=5, drops=["xeno_hide", "thermal_fiber"], voice="sniffer",
         variants=[("plain", "Stilt Strider", {}), ("aurora", "Sky Strider", {"scale": 5.0, "health": 200, "giant": True, "weight": 2})]),
    dict(id="brute", name="Brute", plan="biped", kind="ground", temper="hostile", attack="melee",
         params=dict(body_h=12, body_w=12, body_d=7, leg_len=8, leg_w=4, head=7, arm_len=14, arm_w=4, lean=0.3),
         health=40, damage=8, speed=0.27, armor=4, group=(1, 2), weight=6, drops=["xeno_hide", "xeno_meat"], voice="polar_bear",
         variants=[("stone", "Cave Brute", {}), ("frost", "Snow Brute", {"drops": ["xeno_hide", "thermal_fiber"]}), ("ash", "Ash Brute", {})]),
    dict(id="crab", name="Crab", plan="crab", kind="ground", temper="neutral", attack="melee", swim=True,
         params=dict(body_len=10, body_w=14, body_h=5, leg_len=7, claw=6),
         health=18, damage=4, speed=0.23, armor=7, group=(2, 4), weight=8, drops=["chitin_plate", "xeno_meat"], voice="turtle",
         variants=[("sand", "Shore Crab", {}), ("magma", "Magma Crab", {}), ("frost", "Frost Crab", {}), ("crystal", "Crystal Crab", {}),
                   ("blood", "King Crab", {"scale": 4.0, "health": 160, "damage": 14, "giant": True, "weight": 2, "min_tier": 2,
                                           "group": (1, 1)})]),
    dict(id="ooze", name="Ooze", plan="blob", kind="ground", temper="hostile", attack="melee", hops=True,
         params=dict(size=12),
         health=16, damage=3, speed=0.26, armor=0, group=(2, 4), weight=9, drops=["bio_gel"], voice="slime",
         variants=[("toxic", "Toxic Ooze", {}), ("magma", "Magma Ooze", {}), ("frost", "Frost Ooze", {}), ("crystal", "Crystal Ooze", {}),
                   ("void", "Void Ooze", {"min_tier": 3}), ("gold", "Gold Ooze", {}), ("blood", "Blood Ooze", {})]),
    dict(id="glider", name="Glider", plan="flyer", kind="flyer", temper="hostile", attack="melee",
         params=dict(body_len=6, body_w=4, body_h=4, span=20, head=4, snout=2, chord=6, legs=True),
         health=10, damage=3, speed=0.3, fly=0.6, armor=0, group=(2, 4), weight=8, drops=["xeno_hide"], voice="bat",
         variants=[("stone", "Cave Glider", {}), ("dusk", "Dusk Glider", {}), ("ember", "Ember Glider", {}), ("frost", "Frost Glider", {}),
                   ("toxic", "Plague Glider", {})]),
    dict(id="skyray", name="Skyray", plan="ray", kind="flyer", temper="passive", attack="none",
         params=dict(body_len=18, span=34),
         health=30, damage=0, speed=0.25, fly=0.35, armor=1, group=(1, 3), weight=6, drops=["xeno_hide", "glow_spore"], voice="allay",
         variants=[("deep", "Sky Ray", {}), ("storm", "Storm Ray", {}),
                   ("void", "Void Ray", {"scale": 6.0, "health": 260, "giant": True, "weight": 2, "min_tier": 3, "drops": ["leviathan_scale", "glow_spore"]})]),
    dict(id="wyvern", name="Wyvern", plan="flyer", kind="flyer", temper="hostile", attack="melee",
         params=dict(body_len=16, body_w=7, body_h=7, span=30, head=7, snout=5, chord=12, tail=14, legs=True),
         health=60, damage=9, speed=0.3, fly=0.5, armor=4, group=(1, 1), weight=4, drops=["xeno_hide", "leviathan_scale"], voice="phantom",
         min_tier=2, variants=[("sand", "Sand Wyvern", {}), ("frost", "Frost Wyvern", {}), ("magma", "Magma Wyvern", {}),
                               ("void", "Elder Wyvern", {"scale": 5.0, "health": 420, "damage": 26, "giant": True, "weight": 1,
                                                         "min_tier": 4, "voice": "ender_dragon", "drops": ["leviathan_scale", "titan_core"]})]),
    dict(id="jelly", name="Jelly", plan="jelly", kind="floater", temper="neutral", attack="melee",
         params=dict(size=10, tentacle=12, tentacles=8),
         health=16, damage=3, speed=0.12, fly=0.15, armor=0, group=(2, 5), weight=8, drops=["bio_gel", "glow_spore"], voice="squid",
         variants=[("deep", "Drift Jelly", {}), ("glow", "Glow Jelly", {}), ("storm", "Storm Jelly", {}), ("ember", "Ember Jelly", {}),
                   ("aurora", "Colossal Jelly", {"scale": 7.0, "health": 240, "damage": 10, "giant": True, "weight": 1, "min_tier": 3})]),
    dict(id="moth", name="Moth", plan="flyer", kind="flyer", temper="passive", attack="none",
         params=dict(body_len=6, body_w=3, body_h=3, span=16, head=3, chord=10),
         health=6, damage=0, speed=0.2, fly=0.4, armor=0, group=(2, 5), weight=8, drops=["glow_spore"], voice="bat",
         variants=[("glow", "Lumen Moth", {}), ("ash", "Ash Moth", {})]),
    dict(id="eye", name="Eye", plan="eye", kind="floater", temper="hostile", attack="spit", spit_range=18,
         params=dict(size=10, stalks=5),
         health=18, damage=4, speed=0.15, fly=0.3, armor=1, group=(1, 2), weight=5, drops=["glow_spore", "bio_gel"], voice="ghast", min_tier=2,
         variants=[("blood", "Watcher Eye", {}), ("void", "Void Eye", {"min_tier": 3}), ("frost", "Frost Eye", {}), ("ember", "Ember Eye", {})]),
    dict(id="sandworm", name="Worm", plan="worm", kind="worm", temper="hostile", attack="melee", giant=True,
         worm=dict(segments=14, mode="burrow", spacing=0.95, legs=False, ridge=True),
         params=dict(seg=16, mandibles=3),
         health=180, damage=16, speed=0.45, armor=6, group=(1, 1), weight=2, scale=3.0, min_tier=1,
         drops=["worldeater_fang", "xeno_hide"], voice="warden",
         variants=[("sand", "Dune Worm", {"sol": ["mars"]}), ("frost", "Ice Worm", {}), ("magma", "Magma Worm", {}),
                   ("sand", "Worldeater", {"scale": 7.5, "health": 1200, "damage": 40, "weight": 1, "min_tier": 3,
                                           "worm": dict(segments=40, mode="burrow", spacing=0.95, legs=False, ridge=True),
                                           "voice": "ender_dragon", "drops": ["worldeater_fang", "worldeater_fang", "titan_core"]})]),
    dict(id="burrower", name="Burrower", plan="worm", kind="worm", temper="hostile", attack="melee",
         worm=dict(segments=6, mode="burrow", spacing=0.95, legs=False, ridge=False),
         params=dict(seg=8, mandibles=3),
         health=14, damage=4, speed=0.3, armor=1, group=(1, 3), weight=6, drops=["bio_gel"], voice="silverfish",
         variants=[("stone", "Rock Burrower", {}), ("blood", "Flesh Burrower", {}), ("glow", "Glow Worm", {"temper": "passive"})]),
    dict(id="serpent", name="Serpent", plan="worm", kind="worm", temper="hostile", attack="melee",
         worm=dict(segments=9, mode="surface", spacing=0.9, legs=False, ridge=False),
         params=dict(seg=6, mandibles=2),
         health=18, damage=5, speed=0.3, armor=1, group=(1, 2), weight=7, drops=["xeno_hide", "venom_sac"], voice="spider",
         variants=[("sand", "Sand Serpent", {}), ("jungle", "Jungle Serpent", {}), ("frost", "Frost Serpent", {}),
                   ("magma", "Magma Serpent", {}), ("void", "Void Serpent", {"min_tier": 3})]),
    dict(id="centipede", name="Centipede", plan="worm", kind="worm", temper="hostile", attack="melee",
         worm=dict(segments=12, mode="surface", spacing=0.9, legs=True, ridge=False),
         params=dict(seg=7, mandibles=2),
         health=26, damage=5, speed=0.32, armor=4, group=(1, 1), weight=5, drops=["chitin_plate", "venom_sac"], voice="silverfish",
         variants=[("stone", "Rock Centipede", {}), ("glow", "Glow Centipede", {})]),
    dict(id="eel", name="Eel", plan="worm", kind="worm", temper="hostile", attack="melee", swim=True,
         worm=dict(segments=8, mode="swim", spacing=0.9, legs=False, ridge=True),
         params=dict(seg=6, mandibles=2),
         health=16, damage=4, speed=0.32, armor=0, group=(1, 3), weight=6, drops=["xeno_meat", "bio_gel"], voice="guardian",
         variants=[("deep", "Lake Eel", {}), ("magma", "Lava Eel", {}), ("storm", "Shock Eel", {}),
                   ("deep", "Leviathan", {"scale": 6.0, "health": 700, "damage": 30, "giant": True, "weight": 1, "min_tier": 3,
                                          "worm": dict(segments=30, mode="swim", spacing=0.95, legs=False, ridge=True),
                                          "voice": "elder_guardian", "drops": ["leviathan_scale", "leviathan_scale", "titan_core"]})]),
    dict(id="spitter", name="Spitter", plan="plant", kind="static", temper="hostile", attack="spit", spit_range=14,
         params=dict(stalk=10, head=8),
         health=20, damage=4, speed=0.0, armor=2, group=(1, 3), weight=7, drops=["glow_spore", "venom_sac"], voice="creaking",
         variants=[("jungle", "Spitter Plant", {}), ("frost", "Frost Spitter", {}), ("magma", "Magma Spitter", {})]),
    dict(id="myconid", name="Myconid", plan="mushroom", kind="ground", temper="neutral", attack="melee",
         params=dict(stem=10, cap=14, leg_len=4),
         health=18, damage=3, speed=0.22, armor=1, group=(2, 4), weight=8, drops=["glow_spore"], voice="frog", types=["FUNGAL", "JUNGLE", "TOXIC"],
         variants=[("glow", "Sporeling", {"scale": 0.6}), ("moss", "Shroom Walker", {}), ("blood", "Myconid Elder", {"scale": 2.2, "health": 60})]),
    dict(id="shardling", name="Shardling", plan="sprite", kind="floater", temper="passive", attack="none",
         params=dict(size=5),
         health=8, damage=0, speed=0.15, fly=0.3, armor=4, group=(2, 4), weight=7, drops=["glow_spore"], voice="allay", types=["CRYSTAL", "ICE", "SHATTERED"],
         variants=[("crystal", "Shardling", {}), ("aurora", "Prism Sprite", {})]),
    dict(id="mimic", name="Mimic", plan="mimic", kind="ground", temper="hostile", attack="melee", ambush=True,
         params=dict(size=14),
         health=30, damage=8, speed=0.3, armor=8, group=(1, 1), weight=5, drops=["chitin_plate"], voice="shulker",
         variants=[("stone", "Boulder Mimic", {"sol": ["moon"]}), ("frost", "Ice Mimic", {})]),
    dict(id="tortoise", name="Tortoise", plan="quadruped", kind="ground", temper="passive", attack="none",
         params=dict(body_len=16, body_w=14, body_h=6, leg_len=5, leg_w=4, head=5, shell=7, tail=3, stride=0.5),
         health=40, damage=0, speed=0.12, armor=12, group=(1, 2), weight=6, drops=["chitin_plate", "xeno_meat"], voice="turtle",
         variants=[("stone", "Rock Tortoise", {}), ("magma", "Magma Tortoise", {}),
                   ("moss", "Island Tortoise", {"scale": 9.0, "health": 800, "giant": True, "weight": 1, "min_tier": 3,
                                                "drops": ["titan_core", "chitin_plate"]})]),
    dict(id="stag", name="Stag", plan="quadruped", kind="ground", temper="passive", attack="none",
         params=dict(body_len=14, body_w=7, body_h=7, leg_len=13, leg_w=2, head=6, snout=3, neck=7, tail=3, stride=1.1),
         health=18, damage=0, speed=0.3, armor=0, group=(2, 4), weight=10, drops=["xeno_meat", "xeno_hide"], voice="llama",
         variants=[("glow", "Lumen Stag", {}), ("frost", "Frost Stag", {}), ("ember", "Ember Stag", {})]),
    dict(id="runner", name="Runner", plan="biped", kind="ground", temper="passive", attack="none",
         params=dict(body_h=7, body_w=6, body_d=9, leg_len=12, leg_w=2, head=5, snout=3, lean=0.9, tail=6),
         health=12, damage=0, speed=0.35, armor=0, group=(3, 6), weight=10, drops=["xeno_meat"], voice="frog",
         variants=[("sand", "Dune Runner", {}), ("aurora", "Plume Runner", {})]),
    dict(id="spikeback", name="Spikeback", plan="quadruped", kind="ground", temper="neutral", attack="melee",
         params=dict(body_len=10, body_w=9, body_h=7, leg_len=4, leg_w=3, head=5, snout=2, stride=1.0),
         health=16, damage=4, speed=0.24, armor=6, group=(1, 3), weight=7, drops=["chitin_plate"], voice="armadillo",
         variants=[("stone", "Spikeback", {}), ("crystal", "Crystal Spikeback", {})]),
    dict(id="hydra", name="Hydra", plan="hydra", kind="ground", temper="hostile", attack="spit", spit_range=16, giant=True,
         params=dict(body_len=20, body_w=16, body_h=12, leg_len=8, heads=3),
         health=300, damage=14, speed=0.2, armor=8, group=(1, 1), weight=1, scale=2.8, min_tier=3,
         drops=["titan_core", "venom_sac", "leviathan_scale"], voice="wither",
         variants=[("toxic", "Swamp Hydra", {}), ("magma", "Magma Hydra", {})]),
    dict(id="horror", name="Horror", plan="horror", kind="ground", temper="hostile", attack="melee", min_tier=2,
         params=dict(size=12, tentacle=12, tentacles=6),
         health=45, damage=8, speed=0.24, armor=3, group=(1, 1), weight=4, drops=["bio_gel", "venom_sac"], voice="warden",
         variants=[("deep", "Tentacle Horror", {}), ("void", "Void Horror", {"min_tier": 3})]),
]


def expand():
    """Flattens families x variants into species dicts (without geometry)."""
    out = []
    for fam in FAMILIES:
        for element, name, over in fam["variants"]:
            sid = name.lower().replace("'", "").replace(" ", "_")
            s = {k: v for k, v in fam.items() if k != "variants"}
            s.update(over)
            s["id"] = sid
            s["name"] = name
            s["family"] = fam["id"]
            s["element"] = element
            colours, climates, effect = ELEMENTS[element]
            s.setdefault("climates", climates)
            s["effect"] = effect
            s["colours"] = colours
            out.append(s)
    ids = [s["id"] for s in out]
    assert len(ids) == len(set(ids)), [i for i in ids if ids.count(i) > 1]
    return out
